spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/store_db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: 'create'
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  config:
    import:
      - classpath:messages.properties

#messages:
#  insert_user:
#    title: Cadastro de Usuário
#    success: Usuário cadastrado com sucesso!
#    error: Erro ao cadastrar usuário
#  default:
#    error: Por favor, tente novamente ou contate o suporte caso o erro continue a acontecer.